# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d895a01699d3abf6bf506926a2c6b33e55b39eedc8f74948cafe40c24dcfd5821249e8c83b0586134cc58ce575a9682f48273ab21bb784d5797f9fb81b9bba7

test:
  secret_key_base: b939d85a132bcb405ee5b17f68b8c484deef5322ab307055bc8d05d3ac91b242ed3007ee2f6a4ee378f712eb3e6777347f700870c8fa2605096f64e9c5c06460

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
